### ISSUE TITLE
Events defined with live() are not binded when new HTML is displayed with $.msg()

### ISSUE THREAD

**Issue by cassiomarques** [dreamerslab/jquery.msg#1]
First, thanks for this plugin!

I'm doing something like 

``` js
$.get("/bla", {}, function(html) {
  $.msg({content : ${"#whatever").html(), autoUnblock: false});
});
```

where #whatever is the id of an element that comes as part of the HTML returned by the Ajax call. The dialog appears ok. However, I also have code like:

``` js
$(".blabla").live("click", function(){  ... });
```

When I display the returned HTML with $.msg() the events are not binded using live().

Am I doing something wrong?

Thanks!

**Comment by dreamerslab** [comment]
Hey cassiomarques :)
Can you give more details about what's inside the `live` event handler?

**Comment by ben-lin** [comment]
I'm going to close this issue since there is no further information provide.
