### ISSUE TITLE
RESIZE ISSUE.

### ISSUE THREAD

**Issue by adondero** [dreamerslab/jquery.msg#2]
I am new to jQuery, and I come across your plug-in, and really like it.  I am having  a couple of issues that I am not sure how to fix.
1.  My messages of "Please wait" always appears in the upper left corner.  I have the Center plug-in registered along with the CSS for it.
2.  If I make the screen a smaller so the horizontal scroll bar appears, then use the scroll bar, the DIV that is displayed to not allow clicking on any elements does not cover the items that were off the screen before scrolling.  (Note: the demo link from the following page has the same issue;   http://dreamerslab.com/blog/en/  )

thanks for information or help you can provide.

**Comment by ben-lin** [comment]
Hi adondero I think I need an example. You can put it on http://jsfiddle.net/ or email me at ben@dreamerslab.com 
Otherwise I can't really tell what's happening here.

**Comment by fredchu** [comment]
Hi adondero I fixed a bug of [jquery.center](https://github.com/dreamerslab/jquery.center), and the first issue should be fixed. but I can't find the way to fix the second issue.

Thanks for reporting issues :)
